server:
  port: 9002
spring:
  application:
    name: mocroservice-movie
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: #client url
      defaultZone: http://127.0.0.1:8888/eureka
  instance:
    prefer-ip-address: true  #優先使用該服務的IP位址註冊為url

