server:
  port: 9001
spring:
  application:
    name: mocroserver-user
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=UTF8&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
